version: "3.5"
services:
  nginx1:
    image: nginx:1.13.3
    volumes:
      - ./nginx/local.nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    links:
      - api:api
    ports:
      - 83:80

  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
    volumes:
      - .:/api
    command: ["flask", "run", "--host=0.0.0.0"]